"""Added CSS Variables Column

Revision ID: 058f970b85db
Revises: 95ab6a63135d
Create Date: 2017-06-04 22:51:34.297399

"""

# revision identifiers, used by Alembic.
revision = '058f970b85db'
down_revision = '95ab6a63135d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_css', sa.Column('css_variables', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_css', 'css_variables')
    # ### end Alembic commands ###
