"""Add send_rich_embed fields to guilds and cosmetics

Revision ID: 08f6b59be038
Revises: ecf3e6bf950e
Create Date: 2019-11-06 11:54:01.324095

"""

# revision identifiers, used by Alembic.
revision = '08f6b59be038'
down_revision = 'ecf3e6bf950e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cosmetics', sa.Column('send_rich_embed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('guilds', sa.Column('send_rich_embed', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'send_rich_embed')
    op.drop_column('cosmetics', 'send_rich_embed')
    # ### end Alembic commands ###
