"""Repurposed discordio column to generic invite_link

Revision ID: 0b7761d85555
Revises: f146d173e028
Create Date: 2018-01-13 18:13:51.542372

"""

# revision identifiers, used by Alembic.
revision = '0b7761d85555'
down_revision = 'f146d173e028'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guilds', 'discordio', new_column_name='invite_link', existing_type=sa.String(255))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guilds', 'invite_link', new_column_name='discordio')
    # ### end Alembic commands ###
