"""Renamed webhook icon to guest icon

Revision ID: 109a6025e9ec
Revises: 39815dfbcccb
Create Date: 2017-09-24 00:52:44.038589

"""

# revision identifiers, used by Alembic.
revision = '109a6025e9ec'
down_revision = '39815dfbcccb'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guilds', 'webhook_icon', new_column_name='guest_icon')
    op.alter_column('cosmetics', 'webhook_icon', new_column_name='guest_icon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guilds', 'guest_icon', new_column_name='webhook_icon')
    op.alter_column('cosmetics', 'guest_icon', new_column_name='webhook_icon')
    # ### end Alembic commands ###
