"""Added autorole columns to guild

Revision ID: 12267ce662e9
Revises: 87d043d7917e
Create Date: 2018-07-22 05:35:22.574854

"""

# revision identifiers, used by Alembic.
revision = '12267ce662e9'
down_revision = '87d043d7917e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('autorole_discord', sa.BigInteger(), nullable=True))
    op.add_column('guilds', sa.Column('autorole_unauth', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'autorole_unauth')
    op.drop_column('guilds', 'autorole_discord')
    # ### end Alembic commands ###
