"""Add post_timeout and max_message_length columns to guilds

Revision ID: 176d26252734
Revises: b18fcc759865
Create Date: 2018-03-25 04:04:11.000997

"""

# revision identifiers, used by Alembic.
revision = '176d26252734'
down_revision = 'b18fcc759865'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('max_message_length', sa.Integer(), server_default='300', nullable=False))
    op.add_column('guilds', sa.Column('post_timeout', sa.Integer(), server_default='5', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'post_timeout')
    op.drop_column('guilds', 'max_message_length')
    # ### end Alembic commands ###
