"""Removed various guild columns that pretains to discordapi

Revision ID: 87d043d7917e
Revises: 1d2c2dc41e86
Create Date: 2018-07-20 23:04:28.509870

"""

# revision identifiers, used by Alembic.
revision = '87d043d7917e'
down_revision = '1d2c2dc41e86'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'emojis')
    op.drop_column('guilds', 'channels')
    op.drop_column('guilds', 'roles')
    op.drop_column('guilds', 'icon')
    op.drop_column('guilds', 'owner_id')
    op.drop_column('guilds', 'name')
    op.drop_column('guilds', 'webhooks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('webhooks', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('guilds', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('guilds', sa.Column('owner_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('guilds', sa.Column('icon', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
    op.add_column('guilds', sa.Column('roles', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('guilds', sa.Column('channels', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('guilds', sa.Column('emojis', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
