"""Modified guilds table for discordio capability

Revision ID: 95ab6a63135d
Revises: 32a4d2d7b85f
Create Date: 2017-06-04 05:06:13.118878

"""

# revision identifiers, used by Alembic.
revision = '95ab6a63135d'
down_revision = '32a4d2d7b85f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('discordio', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'discordio')
    # ### end Alembic commands ###
