"""Added webhooks column to guild table

Revision ID: 9bf2adbc33e8
Revises: b1124468bb2e
Create Date: 2017-06-30 07:24:10.700408

"""

# revision identifiers, used by Alembic.
revision = '9bf2adbc33e8'
down_revision = 'b1124468bb2e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('webhooks', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'webhooks')
    # ### end Alembic commands ###
