"""Add unauth_captcha column to guilds

Revision ID: a5780c871aec
Revises: 109a6025e9ec
Create Date: 2017-11-04 01:07:47.658780

"""

# revision identifiers, used by Alembic.
revision = 'a5780c871aec'
down_revision = '109a6025e9ec'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('unauth_captcha', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'unauth_captcha')
    # ### end Alembic commands ###
