"""Added visitor view column to guilds table

Revision ID: b1124468bb2e
Revises: 95ab6a63135d
Create Date: 2017-06-08 06:31:28.953304

"""

# revision identifiers, used by Alembic.
revision = 'b1124468bb2e'
down_revision = '95ab6a63135d'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('visitor_view', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'visitor_view')
    # ### end Alembic commands ###
