"""Add css_limit column to cosmetics

Revision ID: d1b89c41bf16
Revises: f65629d470c6
Create Date: 2017-09-11 01:38:07.771715

"""

# revision identifiers, used by Alembic.
revision = 'd1b89c41bf16'
down_revision = 'f65629d470c6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cosmetics', sa.Column('css_limit', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cosmetics', 'css_limit')
    # ### end Alembic commands ###
