"""Remove keyvalue properties table

Revision ID: d5dcee6894fa
Revises: 66971a97040e
Create Date: 2017-12-29 17:39:24.192424

"""

# revision identifiers, used by Alembic.
revision = 'd5dcee6894fa'
down_revision = '66971a97040e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyvalue_properties')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyvalue_properties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='idx_25223_primary')
    )
    # ### end Alembic commands ###
