"""Added application settings table with donation goal related columns

Revision ID: ecf3e6bf950e
Revises: ce2b9c930a7a
Create Date: 2019-10-12 21:26:27.092295

"""

# revision identifiers, used by Alembic.
revision = 'ecf3e6bf950e'
down_revision = 'ce2b9c930a7a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_goal_progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('donation_goal_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('donation_goal_end', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_settings')
    # ### end Alembic commands ###
