"""Added disabled guilds table

Revision ID: f146d173e028
Revises: d5dcee6894fa
Create Date: 2018-01-05 07:36:58.561149

"""

# revision identifiers, used by Alembic.
revision = 'f146d173e028'
down_revision = 'd5dcee6894fa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disabled_guilds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disabled_guilds')
    # ### end Alembic commands ###
